# https://taskfile.dev

version: '3'

vars:
  GCLOUD_PROJECT: 'side-projects-459513'
  GCLOUD_DEFAULT_ZONE: 'europe-west4-a'
  GCLOUD_DEFAULT_REGION: 'europe-west4'

  # Move these variables to commands
  SERVICE_ACCOUNT: 'etl-developer'  
  ENVIRONMENT: 'test'

tasks:

  # setup-service-account

  # setup-python:
    
  create-airflow-vm:
    # Can i define command specific variables (?)
    - gcloud compute instances create airflow-{{.ENVIRONMENT}}-vm-euwe4a-debian-408f \
      --project={{.GCLOUD_PROJECT}} \
      --zone={{.GCLOUD_DEFAULT_ZONE}}
      --machine-type=e2-micro \
      --network-interface=network-tier=PREMIUM,stack-type=IPV4_ONLY,subnet=default \
      --metadata=enable-osconfig=TRUE \
      --maintenance-policy=MIGRATE \
      --provisioning-model=STANDARD \
      --service-account={{.SERVICE_ACCOUNT}}@{{.GCLOUD_PROJECT}}.iam.gserviceaccount.com \
      --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/trace.append \
      --create-disk=auto-delete=yes,boot=yes,device-name=airflow-{{.ENVIRONMENT}}-vm-euwe4a-debian-408f,image=projects/debian-cloud/global/images/debian-12-bookworm-v20250513,mode=rw,size=10,type=pd-balanced \
      --no-shielded-secure-boot \
      --shielded-vtpm \
      --shielded-integrity-monitoring \
      --labels=goog-ops-agent-policy=v2-x86-template-1-4-0,goog-ec-src=vm_add-gcloud \
      --reservation-affinity=any
    - gcloud compute instances ops-agents policies create goog-ops-agent-v2-x86-template-1-4-0-{{.GCLOUD_DEFAULT_ZONE}} \
      --project={{.GCLOUD_PROJECT}} \
      --zone={{.GCLOUD_DEFAULT_ZONE}}
      --file=config.yaml \
    - gcloud compute resource-policies create snapshot-schedule default-schedule-1 \
      --project={{.GCLOUD_PROJECT}} \
      --region={{.GCLOUD_DEFAULT_REGION}} \
      --max-retention-days=14 \
      --on-source-disk-delete=keep-auto-snapshots \
      --daily-schedule \
      --start-time=20:00 \
    - gcloud compute disks add-resource-policies airflow-{{.ENVIRONMENT}}-vm-euwe4a-debian-408f \
      --project={{.GCLOUD_PROJECT}} \
      --zone={{.GCLOUD_DEFAULT_ZONE}}
      --resource-policies=projects/{{.GCLOUD_PROJECT}}/regions/{{.GCLOUD_DEFAULT_REGION}}/resourcePolicies/default-schedule-1

  enable-gcp-services:
    cmds:
      # Does this skip already activated services (?)
      - echo "Enabling GCP services"
      - gcloud services enable storage-component.googleapis.com
      - gcloud services enable secretmanager.googleapis.com
      - gcloud services enable compute.googleapis.com

  setup-airflow-vm:
    # Commands to run on the Airflow
    uv run playwright install
    # Install UV
    # Install Airflow

  bind-iam-policies-to-deployment-service-account:
    # Define command specific variables (to avoid giving the same account the same right again and again)
    cmds:
      - echo "Bind IAM Policies to Service account {{.SERVICE_ACCOUNT}}"
      - gcloud projects add-iam-policy-binding {{.GCLOUD_PROJECT}} --member=serviceAccount:{{.SERVICE_ACCOUNT}}@{{.GCLOUD_PROJECT}}.iam.gserviceaccount.com --role="roles/storage.admin"
      - gcloud projects add-iam-policy-binding {{.GCLOUD_PROJECT}} --member=serviceAccount:{{.SERVICE_ACCOUNT}}@{{.GCLOUD_PROJECT}}.iam.gserviceaccount.com --role="roles/secretmanager.secretAccessor"
      - gcloud projects add-iam-policy-binding {{.GCLOUD_PROJECT}} --member=serviceAccount:{{.SERVICE_ACCOUNT}}@{{.GCLOUD_PROJECT}}.iam.gserviceaccount.com --role="roles/compute.admin"